owya490/social-sports

frontend/tailwind.config.ts
Updated min width size for screens
=> Tailwind Config

frontend/app/event/[id]/page.tsx, frontend/components/events/EventBanner.tsx, frontend/components/events/EventDescription.tsx, frontend/components/events/EventDetails.tsx, frontend/components/events/EventPayment.tsx, frontend/components/events/RecommendedEvents.tsx
Got rid of payment info / booking areas
Added scrolling on similar events
Added safeguarding against no tags
Fixed padding and resizing issues
=> Redid events and other minor fixes

frontend/components/Filter/FilterDialog.tsx, frontend/services/filterService.ts, frontend/services/locationUtils.ts
refactored applyFilters function to make it cleaner
=> 36 fix filtering implementation bugs

frontend/components/Footer.tsx, frontend/components/events/EventPayment.tsx, frontend/components/events/RecommendedEvents.tsx, frontend/components/home/Hero.tsx, frontend/components/home/PopularEvents.tsx, frontend/components/home/PopularLocations.tsx, frontend/components/home/SearchSport.tsx, frontend/components/mobile/MobileEventDetailFooter.tsx, frontend/components/mobile/MobileNavbar.tsx, frontend/components/mobile/MobileSearchInput.tsx
=> Fixed <a> by replacing with <Link>

frontend/components/utility/UserContext.tsx
To use the context just do this:
const { user } = useUser();
=> Properly added user information into Context

.prettierrc
this is the config 
```
{
"trailingComma": "es5",
"tabWidth": 2,
"semi": true,
"singleQuote": false,
"printWidth": 120
}
```
=> Added prettierrc

frontend/components/events/OrganiserEventCard.tsx
Master was failing pipeline because of a failed import
Fixed the import.
=> Fixed import

frontend/package-lock.json, frontend/package.json
Uninstalled deprecated tailwind, redudant packages: uuid, uuidv4, audit fixed
Security vulnerabilities by having the deprecated Tailwind accidentally installed. Fixed error messages coming from npm i.
Uninstalled Tailwind, uuid, uuidv4 from packages.json
May have some unexpected side effects.
=> Fixed npm issues

frontend/observability/GrafanaFaro.tsx, frontend/observability/logger.ts
Grafana wasn't working, now it is. 
There was a CORS error in prod so i fixed that and plus now we log to console in dev with the same logger!
=> Fixed Grafana Logging

frontend/app/organiser/event/[id]/page.tsx
The CICD build was failing after the latest merge of user sharding due to a change in data structure of AbstractUserData
Added appropriate field to dummyUserData
=> Added missing field fo dummyUserData

frontend/app/event/[id]/page.tsx, frontend/services/src/auth/authService.ts, frontend/services/src/events/eventsService.ts
Emergency change, error not found in previous pull req
=> Can't use useNavigate inside async function

frontend/app/(footer)/event/success/[id]/page.tsx
=> NOISSUE-000 Added dependency array to stop infinite useeffect loop

frontend/services/src/datetimeUtils.ts
=> SPORTSHUB-131 fixed time format

frontend/services/src/firebase.ts
We don't want user session to persist for days. Simple solution until we implement session infrastructure.
=> SPORTSHUB-122 Auto Log User Out on Window Close

frontend/components/events/EventCard.tsx
Event card image would show white but when clicking on the event, the picture would load.
=> SPORTSHUB 135 - White image on event card on dashboard

frontend/components/events/EventPayment.tsx
=> Fixing up the format of the event card

frontend/components/events/RecommendedEvents.tsx, frontend/components/home/PopularEvents.tsx
added in min-h for both carousels, so when its small screen it works
=> SPORTSHUB-144 fixed carousel bug

.firebaserc, .gitignore, functions/.gitignore, functions/deployFunctionToFirebase.sh, functions/lib/constants.py, functions/lib/stripe/checkout.py, functions/lib/stripe/create_account.py
added a script to better deploy our functions, allowing separation between prod and dev
added some auth checks + locked down our CORS policies in prod.
In Prod cors will be limited to https://www.sportshub.net.au
however in dev its *
=> SPORTSHUB-121 Lock Down Functions + Functions Deploy Bash Script

frontend/app/(footer)/event/create/page.tsx, frontend/components/events/create/forms/BasicForm.tsx, frontend/components/events/create/forms/PreviewForm.tsx, frontend/components/organiser/EventDrilldownDetailsPage.tsx
End date is now seperate so multi day events can be created with frontend validation for create event and on organiser event drilldown page.
=> SPORTSHUB-3: End Date implementation

frontend/app/(no-footer)/organiser/event/[id]/page.tsx, frontend/app/(no-footer)/organiser/event/dashboard/page.tsx, frontend/app/(no-footer)/organiser/gallery/page.tsx, frontend/app/(no-footer)/organiser/metrics/page.tsx, frontend/components/navbar/ProfilePic.tsx, frontend/components/organiser/OrganiserNavbar.tsx, frontend/next.config.js
Organiser navbar routing 
profile picture dropdown on navbar has organiser hub now
=> Sportshub-138

frontend/components/events/create/forms/BasicForm.tsx
Event capacity shouldn't be negative.
Frontend check to make sure value is not negative.
=> SPORTSHUB-168: Create event capacity has no check if capacity is negative.

frontend/app/(no-footer)/organiser/event/[id]/page.tsx
=> SPORTSHUB-182 fixed share modal on the wrong pages

frontend/app/(footer)/event/[id]/page.tsx, frontend/components/events/EventDetails.tsx, frontend/components/events/EventPayment.tsx, frontend/components/mobile/MobileEventPayment.tsx
Fixed the mobile view of MobileEventPayment.tsx, added the option to book now, so it works for mobile view, als
o fixed the issue with the 'book now' button appearing when the vacancy of an event is zero, so it just shows the message no tickets avaliable"
=> SPORTSHUB-174, SPORTSHUB-183 - Fixing issues with book now on mobile and 0 vacancy

frontend/app/(footer)/profile/page.tsx, frontend/components/events/create/DescriptionImageForm.tsx
Image upload is fixed if you close and reopen browser
=> SPORTSHUB-151 Added advice for image upload

frontend/app/(no-footer)/organiser/dashboard/page.tsx, frontend/components/events/create/forms/BasicForm.tsx, frontend/services/src/events/eventsService.ts
Also smuggled in fix for access Modifier default value now shows up
=> SPORTSHUB-201 Organiser Dashboard Robustness Increase on missed event

functions/lib/move_inactive_events.py
changing region to hopefully reduce latency
=> NOISSUE-000 Update move inactive events to apse1

frontend/components/events/create/DescriptionRichTextEditor.tsx, frontend/components/events/create/custom-styles.css, frontend/package-lock.json, frontend/package.json
=> SPORTSHUB-178 Fixed functionality of the rich text editor

frontend/components/events/EventCard.tsx, frontend/components/events/EventDetails.tsx
=> SPORTSHUB-135 Image Resizing Issue On Event Card

frontend/app/(footer)/dashboard/page.tsx
No events image is now centred when no events on dashboard
=> SPORTSHUB-180 Centred No Events Image on Dashboard

frontend/components/Footer.tsx
this is what it looks like now! much simpler!
=> SPORTSHUB-173 Nuke old footer and revamp to new

frontend/app/(no-footer)/organiser/event/[id]/page.tsx
=> SPORTSHUB-210 fix share modal

firestore.rules
Temp users get full allow list
=> SPORTSHUB-105 Added TempUsers to firestore rules 

frontend/app/(footer)/event/create/page.tsx, frontend/components/elements/HighlightButton.tsx, frontend/components/events/create/forms/BasicForm.tsx, frontend/components/events/create/forms/PreviewForm.tsx, frontend/components/navbar/ProfilePic.tsx, frontend/package-lock.json
Fixed the state issue when moving back and forth create event. 
Removed some redundant states
Changed out buttons for Highlight Button component
Some refactoring
=>  SPORTSHUB-177 State Preservation

frontend/components/events/EventPayment.tsx, frontend/components/mobile/MobileEventPayment.tsx
When you click on location, maps will open up.
=> SPORTSHUB-217 Maps link in event page

frontend/app/(footer)/dashboard/page.tsx
JIRA link: https://owenyang.atlassian.net/jira/software/c/projects/SPORTSHUB/boards/6?issueParent=10330&selectedIssue=SPORTSHUB-208
=> SPORTSHUB-208: Fix successfully logged in alert being hidden by no search result

frontend/app/(footer)/dashboard/page.tsx, frontend/app/(no-footer)/organiser/dashboard/page.tsx, frontend/app/(no-footer)/organiser/event/dashboard/page.tsx, frontend/app/(no-footer)/organiser/gallery/page.tsx, frontend/app/(no-footer)/organiser/metrics/page.tsx, frontend/components/Filter/OrganiserFilterDialog.tsx, frontend/components/Filter/OrganiserFilterDialogMobile.tsx, frontend/components/UnderConstruction.tsx, frontend/components/organiser/OrganiserNavbar.tsx, frontend/components/organiser/dashboard/OrganiserEventCard.tsx, frontend/package-lock.json
Mobile organiser event dashboard is done, fixed issue where location goes changes organiser event card height
=> SPORTSHUB-223 mobile organiser event dashboard

frontend/components/Footer.tsx
=> SPORTSHUB-235  Changed the routing of the suggestions on the footer 

frontend/components/events/EventCard.tsx
=> SPORTSHUB-213 Fixed shrinking Location Icon

frontend/components/events/create/DescriptionImageForm.tsx
=> SPORTSHUB-207   Validation checks for the image upload

frontend/app/(footer)/event/create/page.tsx, frontend/app/(no-footer)/organiser/event/dashboard/page.tsx, frontend/components/events/EventCard.tsx, frontend/components/events/EventPayment.tsx, frontend/components/events/create/forms/BasicForm.tsx, frontend/components/events/create/forms/PreviewForm.tsx, frontend/components/mobile/MobileEventPayment.tsx, frontend/components/organiser/EventDrilldownDetailsPage.tsx, frontend/components/organiser/EventDrilldownStatBanner.tsx, frontend/components/organiser/dashboard/OrganiserEventCard.tsx, frontend/services/src/maps/mapsService.ts, frontend/utilities/priceUtils.ts, functions/deployFunctionToFirebase.sh, functions/lib/sendgrid/create_event.py, functions/lib/sendgrid/purchase_event.py, functions/lib/stripe/checkout.py, functions/lib/stripe/webhooks.py, functions/lib/utils/priceUtils.py
now we can have $18.88 as the price for events.
Events are now stored as cents in the database.
=> SPORTSHUB-81 Support float pricing

frontend/components/events/EventCard.tsx, frontend/components/events/create/forms/PreviewForm.tsx
"the create event preview card is not longer clickable with the new boolean isPreview in the EventCardProps
"
=> SPORTSHUB-192  Create Event preview page, not longer clickable

frontend/app/(no-footer)/organiser/event/[id]/page.tsx, frontend/components/events/ShareModal.tsx
=> HOTFIX - Fix share modal giving the wrong link to organiser rather than public event page

frontend/services/src/events/eventsService.ts
EmptyPurchase was not empty - need to investigate.
=> HOTFIX - fix fake ticket with addattendee logic.

frontend/app/(no-footer)/organiser/dashboard/page.tsx, frontend/components/organiser/dashboard/OrganiserCheckbox.tsx, frontend/components/organiser/dashboard/OrganiserChecklist.tsx
Added mobile view to organiser dashboard and a mobile navbar for organiser
=> SPORTSHUB-230 Organiser mobile dashboard + Organiser navbar

frontend/components/events/EventPayment.tsx
Alot of people booking old events, adding UI element.
=> HOTFIX Add UI Display for when Event is Concluded

frontend/components/events/create/CreateEventCostSlider.tsx
=> SPORTSHUB-176 fixed the event slider so now it doesnt extend forever

frontend/components/mobile/MobileEventPayment.tsx
oops i forget mobile, added it now
=> SPORTSHUB-270 Add Mobile View for No Booking for Concluded Event

frontend/services/src/filterService.ts
=> SPORTSHUB-255 price dollars convert to cents

frontend/app/(footer)/profile/page.tsx, frontend/components/events/create/DescriptionImageForm.tsx, frontend/package-lock.json, frontend/package.json
Images uploaded too large
New package to compress imgs uploaded
=> SPORTSHUB-284 Upload image size

frontend/components/events/create/forms/TagForm.tsx
=> HOTFIX-Tagging Warning for Event Create

frontend/app/(footer)/event/create/page.tsx, frontend/app/(no-footer)/organiser/dashboard/page.tsx, frontend/components/events/create/forms/BasicForm.tsx, frontend/components/organiser/dashboard/OrganiserAnnouncementBanner.tsx, frontend/interfaces/EventTypes.ts, frontend/services/src/events/eventsUtils/getEventsUtils.ts, functions/lib/stripe/checkout.py
=> SPORTSHUB-263 Pass Through Stripe Fees to Customer

frontend/services/src/events/eventsService.ts
Please make a private event and try changing variables. Verify on firebase that it has actually updated.
=> HOTFIX-Update-Event_Details 

frontend/components/events/EventDetails.tsx, frontend/components/mobile/MobileEventPayment.tsx
=> HOTFIX Mobile Registration Closed

frontend/components/organiser/EventDrilldownDetailsPage.tsx
added a window.location.reload(), after each function that calls to e…dit a field of the event, so the changes can be seen instantly on the frontend, allowing for better clarity on the user side
=> SPORTSHUB-306  Auto-Refresh after editing details

frontend/components/events/EventPayment.tsx, frontend/components/mobile/MobileEventPayment.tsx
=> HOTFIX Added one off gg social 1 ticket purchase

frontend/next.config.js
Removed the redirect from / to dashboard, so now we have a home landin…g page however make sure to clear cache to view it
=> SPORTSHUB-311  Adding of back of home landing page

frontend/app/(footer)/page.tsx, frontend/app/(footer)/sitemap.xml
Removed useless shit on main page and added xml sitemap for google
=> HOTFIX - SEO updates

frontend/app/sitemap.xml
=> Sitemap in right place

frontend/app/layout.tsx
=> Favicon wrong path 

frontend/app/(footer)/login/page.tsx, frontend/app/(footer)/register/page.tsx, frontend/app/(footer)/resetPassword/page.tsx
The login, register and reset password pages had poor user experience. The buttons do not show any changes when used.
Added loading status to buttons when clicked
Improved the experience.
=> SPORTSHUB-317 Improve login/register/resetPassword UX

frontend/app/(footer)/dashboard/page.tsx, frontend/components/mobile/MobileSearchBar.tsx, frontend/components/navbar/Logo.tsx, frontend/components/navbar/SearchBar.tsx
Upon testing prod and prod locally there is an issue with location search. It simply does not work together. 
Example Scenarios:
1. Event = "", Location = "Sydney"
PROD: FAIL
DEV: WORKING
2. Event = "Something", Location = "Sydney"
PROD: SEMI-WORKING
DEV: FAIL
DEV is failing as after a couple of searches it is showing the search of the previous search
3. Event = "Something", Location = ""
PROD: WORKING
DEV: WORKING
I have disabled location search as it is not necessary at the moment and so that we can at least provide a working search to both prod and dev until we revamp the search
Navbar is changed as well
=> SPORTSHUB-319 FIX broken search by disabling location search

functions/lib/functions/deployFunctionsToGCloud.sh, functions/lib/functions/src/main/java/com/functions/events/services/RecurringEventsCronService.java, functions/lib/functions/src/main/java/com/functions/users/models/PrivateUserData.java
hot fix for recurring event functions
=> HOTIFX/ Fix edge cases seen in prod

frontend/app/layout.tsx
Changed heading from Sports Hub to SPORTSHUB as per Owen's request
=> HOTFIX: Change Tab Heading

frontend/components/organiser/dashboard/OrganiserEventCard.tsx
=> HOTFIX change organiser event card to remove "Per Person"

frontend/next-env.d.ts, functions/lib/functions/deployFunctionsToGCloud.sh, functions/lib/functions/src/main/java/com/functions/events/controllers/CreateEventEndpoint.java, functions/lib/functions/src/main/java/com/functions/events/controllers/CreateRecurrenceTemplateEndpoint.java, functions/lib/functions/src/main/java/com/functions/events/controllers/RecurringEventsCronEndpoint.java, functions/lib/functions/src/main/java/com/functions/events/controllers/UpdateRecurrenceTemplateEndpoint.java, functions/lib/functions/src/main/java/com/functions/events/models/AbstractEventData.java, functions/lib/stripe/checkout.py
Currently getting errors from events created from recurring events related to price not being valid. Curious to see what the price value is being retrieved as.
=> HOTFIX added additional logging to price + added EventLink to java EventData object + changing Price to Integer from Double

.github/workflows/master_ci.yml, .github/workflows/sportshub_cloud_functions_deploy_ci.yml
Fix this pipeline error with duplicate 'deploy' id: https://github.com/owya490/social-sports/actions/runs/13500845317
Also forgot to set python firebase functions to deploy for prod
=> HOTFIX/ add prod to python deploy and fix ids in master_ci.yml

frontend/app/layout.tsx, frontend/app/sitemap.xml, frontend/next.config.js
Added description for google search, at the moment for dashboard there is no description
Removed landing page and redirect to /dashboard and changed sitemap as needed
=> SPORTSHUB-342 Google Search Description

frontend/services/src/forms/formsServices.ts
Was needed for forms
Get forms for specific users 
Get active and inactive form for specific users
=> SPORTSHUB- 338  - Getting Forms on Users in the Service Layer

frontend/app/(footer)/forms/[formId]/[eventId]/view-form/page.tsx, frontend/app/(footer)/forms/forms-submitted/page.tsx, frontend/app/(no-footer)/organiser/forms/[formId]/form-editor/page.tsx, frontend/app/(no-footer)/organiser/forms/[formId]/form-preview/page.tsx, frontend/app/(no-footer)/organiser/forms/[formId]/form-responses/page.tsx, frontend/app/(no-footer)/organiser/forms/forms-gallery/page.tsx
=> SPORTSHUB-344 Stubbed out frontend files

functions/lib/stripe/checkout.py
should be based on entire order amount, not singular ticket amount
=> HOTFIX Updating pricing surcharge calculation logic

frontend/components/DownloadCsvButton.tsx, frontend/components/organiser/event/attendee/EventDrilldownManageAttendeesPage.tsx
Mobile view of export attendees was broken
Inserted an icon
=> SPORTSHUB-355 Mobile Issue w/ Export CSV

frontend/app/(footer)/dashboard/page.tsx, frontend/app/(footer)/user/[id]/page.tsx, frontend/app/globals.css, frontend/components/Footer.tsx
syrio at the bottom, we want at top
=> HOTFIX Sort events by access count

frontend/app/(no-footer)/organiser/event/[id]/page.tsx, frontend/app/(no-footer)/organiser/recurring-events/[id]/page.tsx, frontend/app/(no-footer)/organiser/settings/page.tsx, frontend/components/elements/LabelledSwitch.tsx, frontend/components/organiser/mobile/MobileEventDrilldownNavTabs.tsx, frontend/components/organiser/recurring-events/RecurringTemplateDrilldownSidePanel.tsx, frontend/components/organiser/settings/OrganiserSettingsCard.tsx, frontend/components/organiser/settings/OrganiserSettingsStripeCard.tsx, frontend/interfaces/UserTypes.ts, functions/lib/functions/src/main/java/com/functions/users/models/PrivateUserData.java, functions/lib/sendgrid/purchase_event.py
STV wanted ticket emails for every purchase of ticket on the attendees side
=> SPORTSHUB-368 Organiser ticket emails

frontend/services/src/fulfilment/fulfilmentServices.ts
=> HOTIFX Turn off syrio jersey fulfilment

frontend/services/src/fulfilment/fulfilmentServices.ts
=> NOISSUE Enable forms for jpnau

functions/lib/stripe/checkout.py
=> HOTFIX allow free events
